- hosts: localhost
  become: true
  tasks:
    - name: Update the system
      dnf:
        name: "*"
        state: latest

    - yum:
        name: yum-utils
        state: present

    - name: Install docker
      include_role:
        name: install-docker